<script setup lang="ts">
import { nextTick, onMounted, watch } from 'vue'
import { useData, useRoute } from 'vitepress'
import {
  hideReadEnabled,
  loadReadState,
  markRead,
  readSet,
  videoIdFromHref,
} from './readState'

const route = useRoute()
const { frontmatter } = useData()

// Reading a summary page is what marks it read — no button required.
function markCurrentPage(): void {
  const id = frontmatter.value?.video_id
  if (typeof id === 'string' && id) markRead(id)
}

// The index cards are generated by digest.py as plain anchors, so read state is
// applied here rather than baked into the markup the pipeline owns.
function decorateCards(): void {
  document.querySelectorAll<HTMLAnchorElement>('a.video-card').forEach((card) => {
    const id = videoIdFromHref(card.getAttribute('href') ?? '')
    card.classList.toggle('is-read', !!id && readSet.value.has(id))
  })

  // A channel whose cards are all filtered out shouldn't leave a stray heading.
  document.querySelectorAll<HTMLElement>('.video-grid').forEach((grid) => {
    const cards = [...grid.querySelectorAll<HTMLElement>('a.video-card')]
    const emptied =
      hideReadEnabled.value && cards.length > 0 && cards.every((c) => c.classList.contains('is-read'))
    grid.classList.toggle('channel-emptied', emptied)
    const heading = grid.previousElementSibling
    if (heading?.tagName === 'H2') heading.classList.toggle('channel-emptied', emptied)
  })
}

function apply(): void {
  document.documentElement.classList.toggle('hide-read', hideReadEnabled.value)
  decorateCards()
}

onMounted(() => {
  loadReadState()
  markCurrentPage()
  apply()
})

// SPA navigation swaps content without a reload, so re-apply on every route
// change and whenever read state or the filter changes.
watch(
  () => route.path,
  async () => {
    markCurrentPage()
    await nextTick()
    apply()
  }
)
watch([readSet, hideReadEnabled], () => nextTick().then(apply), { deep: true })
</script>

<template><span class="read-tracker" hidden /></template>
